### ISSUE TITLE
Build plugins on linux

### ISSUE THREAD

**Issue by fmahiant** [itom-project/plugins#35]
Hi,
I would like to build a plugin using linux (it ease the setup of CI worker like jenkins, github action, ...)
Can I find somewhere any tips on how to start ? 
The current documentation explains in depth the process for Windows, but not for linux. moreover, it seems that it so no easy to build plugin without building Itom itself. 
Am I wrong ?

Regards,
Fred.

**Comment by photoniker** [comment]
Hi Fred, 

there is no specific difference for Plugin programming in Linux. 

First you need to compile itom from sources AS described here 
https://itom-project.github.io/latest/docs/02_installation/install_build_from_source.html

Plugin programming is described in that documentation 
https://itom-project.github.io/latest/docs/07_plugins/development/plugin-development.html 

To start a new Plugin you can find in the itom repo a plugintemplate folder to copy the Plugin sources files.

Cheers Johann.

**Comment by fmahiant** [comment]
Thank you very much,  
I had missed the part about compiling itom in linux.
It's much clearer now.

Regards, 
Fred.

**Comment by photoniker** [comment]
Great,

Unfortunatly there are no YouTube how to Clips... Would be helpful...
